### ISSUE TITLE
Ошибка получения листа

### ISSUE THREAD

**Issue by iskizreal** [Alexell/MMProBumpBot#1]
`Unknown error while Performing tasks: 400, message='Bad Request', url=URL('https://api.mmbump.pro/v1/task-list/complete')`
Видимо поменялся адрес?

**Comment by Alexell** [comment]
Если бы поменялся адрес, было бы 404, а у нас 400, значит формат запроса поменялся. Проверю.

**Comment by Alexell** [comment]
Нет, формат не поменялся. Тогда, вероятно, бот пытается получить награду за задачу, которую по ошибке считает выполненной. Какая у вас задача выполнена была, для которой бот не смог получить награду и была ли такая вообще?
