### ISSUE TITLE
Too many errors

### ISSUE THREAD

**Issue by m-a-prod** [Alexell/MMProBumpBot#3]
Привет, у меня ферма на 100 аккаунтов, и половину из них (штук 10-20) работает исправно, но остальное выдает такое
![image](https://github.com/user-attachments/assets/d4cd0c83-5146-45b4-a294-f3569739c038)
Я хз че с этим делать, может задержек не хватает?

**Comment by Alexell** [comment]
Судя по "Connection refused", проблема, вероятно в прокси. Что касается задержек, я могу сделать как в X Empire Bot задержки перед запуском сессий и дополнительные задержки в логике.

**Comment by m-a-prod** [comment]
Возможно, надо прокси поменять попробовать, просто не было времени заниматься всем этим 😁 А рандомные задержки перед запуском сессий полезное дело, сейчас все так делают.

**Comment by Alexell** [comment]
В течение дня сделаю.
