### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by WanterDehka** [Alexell/MMProBumpBot#5]
Бот поработает несколько часов потом выдает такую ошибку, спустя несколько часов опять пытается авторизироваться, но уже не может, в чем может быть проблема? питон 3,10
https://i.postimg.cc/50dTHJzJ/24-08-2024-112657.jpg

**Comment by Alexell** [comment]
К сожалению, я не могу особо ничего подсказать. Это чисто виндовая проблема, похоже что-то мешает боту пользоваться сетью (интернетом). Посмотрите в сторону брандмауера и/или антивируса.

**Comment by WanterDehka** [comment]
> К сожалению, я не могу особо ничего подсказать. Это чисто виндовая проблема, похоже что-то мешает боту пользоваться сетью (интернетом). Посмотрите в сторону брандмауера и/или антивируса.

Да нет, винда считай чистая, вроде ничего не должно мешать. Кручу еще маска твоего, там вообще все супер летает)
Спасибо за ответ, буду копать тогда)))
