### ISSUE TITLE
Создание сессии

### ISSUE THREAD

**Issue by Akad3m1k** [Alexell/MMProBumpBot#7]
Просто висит на создании сессии, подскажите пожалуйста, как решить данную проблему?
Версия Python 3.10
![image](https://github.com/user-attachments/assets/4d2016c1-e766-46cb-8a09-03fb9a1466dc)

![image](https://github.com/user-attachments/assets/d346c065-c65c-4911-b90d-509867d03aa8)

**Comment by Akad3m1k** [comment]
Решено.
Не запускалось из-за отставания системного времени на 2 минуты.
После синхронизации проблема решилась.

Рекомендуемые NTP-серверы для синхронизации:

0.ru.pool.ntp.org;
1.ru.pool.ntp.org;
ntp0.NL.net;
ntp2.vniiftri.ru;
ntp.ix.ru;
ntps1-1.cs.tu-berlin.de.

**Comment by Alexell** [comment]
Такое редко, но уже писали в Issue в другом моем боте, видимо фишка с временем это какая-то особенность Pyrogram/Telegram. Благодарю за информацию по решению, теперь хоть буду знать, что людям отвечать.
