### ISSUE TITLE
Бот перестал клеймить, ошибки 400, 403

### ISSUE THREAD

**Issue by Nord1cWarr1or** [Alexell/MMProBumpBot#8]
```
Unknown error when Claiming: 400, message='Bad Request', url=URL('https://api.mmbump.pro/v1/farming/finish')
Unknown error when Start Farming: 403, message='Forbidden', url=URL('https://api.mmbump.pro/v1/farming/start')
```

**Comment by Alexell** [comment]
Все работает. Ошибки иногда выдает сам Blum. Я как то с телефона заходил, так он не реагировал на некоторые функции, включая Claim (под капотом выдавал ошибки).
![изображение](https://github.com/user-attachments/assets/beadad92-5d2b-4f18-8fb1-ea0750f5a024)

**Comment by Alexell** [comment]
Все работает. У меня нет никаких ошибок аж с 15 числа. А вот 14 числа были ошибки, как у вас, но это проблема на стороне сервера игры, она разрешилась сама собой и бот дальше работал без проблем и моего вмешательства.
![изображение](https://github.com/user-attachments/assets/1475fc7a-71ef-4012-84f2-f7a263d25136)

**Comment by Nord1cWarr1or** [comment]
Понял, спасибо
